# Generated by Django 5.1.7 on 2025-10-11 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactformmodel",
            old_name="date",
            new_name="created_date",
        ),
    ]
